<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-UR9D5D0" failures="0" tests="2" name="formation.tests.ErrorValidationsTest" time="26.139" errors="1" timestamp="2024-09-29T23:32:12 CEST" skipped="0">
  <testcase classname="formation.tests.ErrorValidationsTest" name="LoginErrorValidation" time="14.808"/>
  <system-out/>
  <testcase classname="formation.tests.ErrorValidationsTest" name="ProductErrorValidation" time="11.331">
    <error message="Le produit ZARA COAT 33 n&#039;a pas été trouvé." type="java.lang.IllegalArgumentException">
      <![CDATA[java.lang.IllegalArgumentException: Le produit ZARA COAT 33 n'a pas été trouvé.
at Formation_test.pageObjects.ProductCatalogue.addProductToCart(ProductCatalogue.java:53)
at formation.tests.ErrorValidationsTest.ProductErrorValidation(ErrorValidationsTest.java:34)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </error>
  </testcase> <!-- ProductErrorValidation -->
  <system-out/>
</testsuite> <!-- formation.tests.ErrorValidationsTest -->
